# Generated by Django 6.0.3 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_participatingmeetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingmeetup',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='participatingmeetup',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
