# Generated by Django 6.0.3 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_participatingmeetup_website_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingmeetup',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='meetup_logos/'),
        ),
    ]
