# Generated by Django 6.0.5 on 2026-05-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_mailinglistsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingmeetup',
            name='calendar_group_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
